### ISSUE TITLE
这个对python的依赖版本是多少啊？

### ISSUE THREAD

**Issue by jalena** [leeyiw/dnspod_ddns#3]
Python 3.6.2

抛出以下错误！

`F:\python\dnspod_ddns>pip install dnspod
Collecting dnspod
  Using cached dnspod-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Jalena\AppData\Local\Temp\pip-build-ybw909h0\dnspod\setup.py", line 7, in <module>
        execfile(convert_path('dnspod/version.py'))
    NameError: name 'execfile' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Jalena\AppData\Local\Temp\pip-build-ybw909h0\dnspod\`

**Comment by leeyiw** [comment]
你好 只在Python 2.7下做过测试，需要适配3可以提PR给我
